In [ ]:
import pandas as pd

# Load the parquet file into a DataFrame
df = pd.read_parquet('/content/shopping_queries_dataset_examples.parquet')

# Display the first 5 rows of the DataFrame

df

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train
1,1,revent 80 cfm,0,B07X3Y6B1V,us,E,0,1,train
2,2,revent 80 cfm,0,B07WDM7MQQ,us,E,0,1,train
3,3,revent 80 cfm,0,B07RH6Z8KW,us,E,0,1,train
4,4,revent 80 cfm,0,B07QJ7WYFQ,us,E,0,1,train
...,...,...,...,...,...,...,...,...,...
2621283,2621283,�����j�[�h�p�[�x abrasus,130651,B0063ASUY4,jp,E,0,1,test
2621284,2621284,�����j�[�h�p�[�x abrasus,130651,B0062EZYIG,jp,E,0,1,test
2621285,2621285,�����j�[�h�p�[�x abrasus,130651,B07H8MWBZN,jp,S,0,1,test
2621286,2621286,�����j�[�h�p�[�x abrasus,130651,B00IZH4T9S,jp,E,0,1,test
2621287,2621287,�����j�[�h�p�[�x abrasus,130651,B07R536DG1,jp,E,0,1,test

In [ ]:
# Drop duplicate rows based on the 'query' column
df_unique_queries = df.drop_duplicates(subset=['query']).copy()

print(f"Original DataFrame shape: {df.shape}")
print(f"DataFrame with unique queries shape: {df_unique_queries.shape}")

display(df_unique_queries.head())

Original DataFrame shape: (2621288, 9)
DataFrame with unique queries shape: (130193, 9)

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train
16,16,!awnmower tires without rims,1,B075SCHMPY,us,I,1,1,train
32,32,!qscreen fence without holes,2,B07D7TBSGH,us,I,1,1,test
70,70,!solid camiseta sin manga,3,B08TQH4RBB,es,E,1,1,train
109,109,"""vitamina c""",4,B088X4B517,es,E,0,1,test

In [ ]:
import numpy as np

# Keep only the 'query' column
df_queries_with_random_id = df_unique_queries[['query']].copy()

# Generate a new column with random integers from 1 to 100,000
df_queries_with_random_id['random_id'] = np.random.randint(1, 100001, size=len(df_queries_with_random_id))

# Display the head of the new DataFrame
display(df_queries_with_random_id.head())

                            query  random_id
0                   revent 80 cfm      22478
16   !awnmower tires without rims      56879
32   !qscreen fence without holes      47665
70      !solid camiseta sin manga      49295
109                  "vitamina c"      55797

In [ ]:
# Rename the 'random_id' column to 'count'
df_queries_with_random_id = df_queries_with_random_id.rename(columns={'random_id': 'count'})

# Display the head of the DataFrame with the renamed column
display(df_queries_with_random_id.head())

                            query  count
0                   revent 80 cfm  22478
16   !awnmower tires without rims  56879
32   !qscreen fence without holes  47665
70      !solid camiseta sin manga  49295
109                  "vitamina c"  55797

In [ ]:
df_typeahead = pd.read_csv('typeahead_dataset.csv')

In [ ]:
df_typeahead = df_typeahead.dropna(subset=['query'])
df_typeahead = df_typeahead[df_typeahead['query'].str.strip() != '']
print(f"DataFrame shape after removing null/empty queries: {df_typeahead.shape}")

DataFrame shape after removing null/empty queries: (130193, 2)

In [ ]:
df_typeahead.to_json('typeahead_dataset.json', orient='records', indent=4)
print("Cleaned DataFrame saved as 'typeahead_dataset.json'")

Cleaned DataFrame saved as 'typeahead_dataset.json'

In [ ]:
df_queries_with_random_id.to_csv('typeahead_dataset.csv', index=False)
print("DataFrame saved as 'typeahead_dataset.csv'")

DataFrame saved as 'typeahead_dataset.csv'